-- BoardBagFees.com — expand from 32 to 60 airlines
-- Prepared 2026-08-11. Safe to run more than once.
-- Public summaries below are initial official-policy snapshots; n8n/Gemini remains the ongoing source-of-truth updater.

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('JetBlue','jetblue',33,'Connection',false,'Special sports-gear rules; verify route-specific fee','Surfboards handled under JetBlue Sports Gear rules; route restrictions may apply',null,'⚪ No comparable U.S. DOT baggage-handling data','https://www.jetblue.com/help/sports-gear','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Spirit Airlines','spirit-airlines',34,'Connection',false,'Special surfboard charge; up to 2 boards in one case for the same charge','Up to 100 lb; oversize/overweight fees waived because a special surfboard charge applies; destination restrictions exist',2,'⚪ No comparable U.S. DOT baggage-handling data','https://customersupport.spirit.com/en-US/category/article/KA-01154','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Frontier Airlines','frontier-airlines',35,'Connection',false,'Special/oversized sports equipment rules apply','Frontier directs travelers to its Special & Fragile Items rules; verify surfboard dimensions before booking',null,'⚪ No comparable U.S. DOT baggage-handling data','https://faq.flyfrontier.com/help/bags-seats-general-info-can-i-bring-sporting-or-musical-equipment-with-me','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Aeromexico','aeromexico',36,'Connection',false,'Special sports-baggage fee','Surf equipment accepted as special baggage; price varies by market/season',2,'⚪ No comparable U.S. DOT baggage-handling data','https://www.aeromexico.com/en-us/travel-information/baggage/special-baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Copa Airlines','copa-airlines',37,'Connection',false,'Special sports-luggage rules apply','Surfboard rules are listed under Copa special sports luggage; advance verification recommended',null,'⚪ No comparable U.S. DOT baggage-handling data','https://www.copaair.com/en-us/travel-information/baggage-information/sports-luggage/','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Avianca','avianca',38,'Connection',false,'Paid sports-equipment fee on most surf routes','Up to 3 surfboards in one bag; bag may be up to 3.7 m / 12 ft; weight limits apply',2,'⚪ No comparable U.S. DOT baggage-handling data','https://ayuda.avianca.com/hc/en-us/articles/13082634010139-Can-I-bring-my-sports-equipment','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('LATAM Airlines','latam-airlines',39,'Connection',false,'Special sports baggage; extra charge can apply','Surf equipment may contain up to 3 boards; special-baggage limits apply',3,'⚪ No comparable U.S. DOT baggage-handling data','https://www.latamairlines.com/us/en/help-center/faq/baggage/special/sports-baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('GOL','gol',40,'Connection',false,'Sports equipment may travel as baggage within permitted limits','If sports equipment exceeds permitted weight/dimensions it is handled as separate baggage',3,'⚪ No comparable U.S. DOT baggage-handling data','https://www.voegol.com.br/en-US/web/guest/nh/bagagens','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Azul Brazilian Airlines','azul-brazilian-airlines',41,'Connection',false,'Special service fee','Up to 3 boards per bag; surfboard maximum 3.20 m, or 1.90 m on ATR aircraft; excess-weight fees can also apply',2,'⚪ No comparable U.S. DOT baggage-handling data','https://www.voeazul.com.br/us/en/your-trip/plan/luggage/special-luggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('British Airways','british-airways',42,'Connection',false,'Included as checked baggage when within allowance','Surfboard up to 240 cm long x 75 cm wide and under 23 kg; not accepted through London City (LCY)',5,'⚪ No comparable U.S. DOT baggage-handling data','https://www.britishairways.com/content/en/gb/information/baggage-essentials/sports-equipment','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Air France','air-france',43,'Connection',false,'Special sports-equipment rules and fees','Surfboards are special baggage; verify current route-specific surf fee and size rules before booking',2,'⚪ No comparable U.S. DOT baggage-handling data','https://wwws.airfrance.us/information/bagages/bagages-speciaux-hors-format-airfrance','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('KLM','klm',44,'Connection',false,'Can replace an item of checked luggage','Surfing equipment up to 300 cm total dimensions; typically up to 23 kg Economy/Premium Comfort or 32 kg Business',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.klm.com/information/baggage/special-baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Lufthansa','lufthansa',45,'Connection',false,'Sports baggage; free allowance or special-rate rules depend on fare/allowance','Shortboard up to 200 cm; longboard/windsurf board up to 315 cm; max 32 kg; advance registration recommended',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.lufthansa.com/au/en/add-sports-baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('SWISS','swiss',46,'Connection',false,'Sports baggage; included if within allowance, otherwise special rates','Shortboards up to 200 cm; longboards accepted under separate rules; max 32 kg; advance registration recommended',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.swiss.com/xx/en/prepare/baggage/sports-equipment.html','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Iberia','iberia',47,'Connection',false,'Paid special sports baggage','Surf/kite/wave board up to 3.5 m; one set per passenger; space availability applies',3,'⚪ No comparable U.S. DOT baggage-handling data','https://www.iberia.com/us/luggage/special/','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('TAP Air Portugal','tap-air-portugal',48,'Connection',false,'Can be included in hold allowance within standard limits; special handling/fees can apply when oversized','Sports equipment max 32 kg; standard free-baggage dimensions are 158 cm unless a sport-specific exception applies',3,'⚪ No comparable U.S. DOT baggage-handling data','https://www.flytap.com/en-hu/information/baggage/sports-equipment','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('easyJet','easyjet',49,'Connection',false,'Paid large sports equipment','Surfboards/windsurfers are large sports equipment with a 32 kg allowance; space limits apply',2,'⚪ No comparable U.S. DOT baggage-handling data','https://www.easyjet.com/en/help/baggage/sports-equipment','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Ryanair','ryanair',50,'Connection',false,'Paid sporting-equipment fee','Surfboards must travel in the hold; sporting equipment allowance is 20 kg, with excess-weight fees above that',1,'⚪ No comparable U.S. DOT baggage-handling data','https://help.ryanair.com/hc/en-us/articles/12888834233489-What-sports-equipment-can-I-bring-on-board','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Etihad Airways','etihad-airways',51,'Connection',false,'Included in checked baggage allowance','Surfboards and water-sports boards up to 300 cm; longer items must go as cargo',5,'⚪ No comparable U.S. DOT baggage-handling data','https://www.etihad.com/en/help/baggage-information/special-equipment-and-other-items','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Garuda Indonesia','garuda-indonesia',52,'Connection',false,'Additional free sporting-equipment allowance for one surfboard','Surfboard under 23 kg and under 300 cm on qualifying aircraft; smaller-aircraft limits can be much shorter',5,'⚪ No comparable U.S. DOT baggage-handling data','https://www.garuda-indonesia.com/static/en/garuda-indonesia-experience/baggage-info.html','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Batik Air Indonesia','batik-air-indonesia',53,'Connection',false,'Special handling fee per piece and per segment','Maximum 23 kg; max 230 cm on jet aircraft and 200 cm when a Wings Air segment is involved',3,'⚪ No comparable U.S. DOT baggage-handling data','https://help.batikair.com/article/conditions-for-bringing-a-surfboard-on-batik-air-indonesia-flights/748','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Scoot','scoot',54,'Connection',false,'Counts toward pre-purchased checked baggage allowance','Sporting equipment including surfboards is accepted within purchased allowance; no checked item above 32 kg',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.flyscoot.com/en/plan/booking-your-flight/baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Thai Airways','thai-airways',55,'Connection',false,'Flat surfboard charge','USD 150 up to 2 m; USD 300 over 2 m',1,'⚪ No comparable U.S. DOT baggage-handling data','https://www.thaiairways.com/en-us/content/baggage/special-baggage/','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('SriLankan Airlines','srilankan-airlines',56,'Connection',false,'One surf/windsurf set can be included in free baggage allowance; excess rules apply','Maximum weight 32 kg; additional sets can incur special/excess charges',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.srilankan.com/en_uk/plan-and-book/luggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('China Southern Airlines','china-southern-airlines',57,'Connection',false,'Special surfboard charges on international flights','International surfboards up to 300 cm handled under excess-baggage rules; advance agreement may be required',2,'⚪ No comparable U.S. DOT baggage-handling data','https://www.csair.com/newh5/en/tourguide/luggage_service/special_baggage/surfing/','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('China Eastern Airlines','china-eastern-airlines',58,'Connection',false,'Special baggage fee','Surfboards up to 203 cm have published special fees; larger items require airline approval; max single-piece weight limits apply',1,'⚪ No comparable U.S. DOT baggage-handling data','https://global.ceair.com/global/en_static/Announcement/BaggageService/FeeRegulationsforExcessSpecialBaggage/','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('STARLUX Airlines','starlux-airlines',59,'Connection',false,'Included in checked baggage allowance','Up to 2 surfboards per bag; oversized sporting equipment up to 292 cm has no oversize fee; larger items need authorization',5,'⚪ No comparable U.S. DOT baggage-handling data','https://www.starlux-airlines.com/en-TW/check-in-fly/baggage-information/special-baggage','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Air India','air-india',60,'Connection',false,'Part of free baggage allowance plus a sports-equipment handling fee on many fares','Maximum 300 cm / 118 in combined dimensions and 32 kg / 70 lb; larger items must travel as cargo',4,'⚪ No comparable U.S. DOT baggage-handling data','https://www.airindia.com/in/en/travel-information/baggage-guidelines/special-baggage.html','2026-08-11',false,'Added in the 60-airline global expansion from the airline’s official baggage/sports policy. Automated structured extraction baseline pending.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

-- Verify total active rows. Expect 60.
select count(*) as active_airlines from public.airline_surf_policies where active = true;

-- Show the 28 new rows.
select airline, slug, surf_rating_score, surf_rating, policy_url from public.airline_surf_policies where sort_rank between 33 and 60 order by sort_rank;