-- BoardBagFees Quality Control Layer v1
-- Run once in Supabase SQL Editor. Safe to re-run.

create table if not exists public.airline_policy_qc_log (
  id bigint generated by default as identity primary key,
  airline text,
  policy_url text not null,
  confidence numeric,
  severity text not null default 'green',
  status text not null default 'auto_applied',
  reasons jsonb not null default '[]'::jsonb,
  old_snapshot jsonb,
  proposed_payload jsonb not null,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  review_action text,
  review_notes text
);

create index if not exists airline_policy_qc_log_status_created_idx
  on public.airline_policy_qc_log(status, created_at desc);
create index if not exists airline_policy_qc_log_policy_url_idx
  on public.airline_policy_qc_log(policy_url, created_at desc);

alter table public.airline_policy_qc_log enable row level security;
revoke all on table public.airline_policy_qc_log from anon, authenticated;
grant all on table public.airline_policy_qc_log to service_role;

-- Preserve the updater function that already works. We rename it only once,
-- then install a QC wrapper under the original RPC name so n8n needs no changes.
do $$
declare
  v_oid oid;
begin
  if to_regprocedure('public.process_airline_policy_extraction_unchecked(text,text,jsonb,numeric,text,text,integer,text,text)') is null
     and not exists (
       select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace
       where n.nspname='public' and p.proname='process_airline_policy_extraction_unchecked'
     ) then
    select p.oid into v_oid
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and p.proname='process_airline_policy_extraction'
      and p.pronargs=9
    order by p.oid
    limit 1;
    if v_oid is null then
      raise exception 'Existing process_airline_policy_extraction RPC was not found. Stop here; nothing was changed.';
    end if;
    execute format('alter function %s rename to process_airline_policy_extraction_unchecked', v_oid::regprocedure);
  end if;
end $$;

create or replace function public.process_airline_policy_extraction(
  p_policy_url text,
  p_airline text,
  p_facts jsonb,
  p_confidence numeric,
  p_surfboard_treatment text,
  p_size_rule text,
  p_surf_rating_score integer,
  p_surf_rating text,
  p_notes text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current record;
  v_old_facts jsonb := '{}'::jsonb;
  v_old_fee text;
  v_new_fee text;
  v_old_baggage text;
  v_new_baggage text;
  v_old_has boolean;
  v_new_has boolean;
  v_old_amount numeric;
  v_new_amount numeric;
  v_reasons text[] := array[]::text[];
  v_hard_hold boolean := false;
  v_medium_change boolean := false;
  v_severity text := 'green';
  v_log_id bigint;
  v_payload jsonb;
  v_old_snapshot jsonb;
  v_pending_id bigint;
begin
  select airline, policy_url, policy_facts, surfboard_treatment, size_rule,
         surf_rating_score, surf_rating, last_checked
  into v_current
  from public.airline_surf_policies
  where policy_url = p_policy_url
  limit 1;

  if found then
    v_old_facts := coalesce(v_current.policy_facts, '{}'::jsonb);
    v_old_snapshot := jsonb_build_object(
      'airline', v_current.airline,
      'policy_url', v_current.policy_url,
      'policy_facts', v_current.policy_facts,
      'surfboard_treatment', v_current.surfboard_treatment,
      'size_rule', v_current.size_rule,
      'surf_rating_score', v_current.surf_rating_score,
      'surf_rating', v_current.surf_rating,
      'last_checked', v_current.last_checked
    );
  else
    v_old_snapshot := null;
  end if;

  v_payload := jsonb_build_object(
    'p_policy_url', p_policy_url,
    'p_airline', p_airline,
    'p_facts', p_facts,
    'p_confidence', p_confidence,
    'p_surfboard_treatment', p_surfboard_treatment,
    'p_size_rule', p_size_rule,
    'p_surf_rating_score', p_surf_rating_score,
    'p_surf_rating', p_surf_rating,
    'p_notes', p_notes
  );

  v_old_fee := nullif(trim(v_old_facts->>'fee_text'), '');
  v_new_fee := nullif(trim(coalesce(p_facts->>'fee_text','')), '');
  v_old_baggage := lower(coalesce(v_old_facts->>'baggage_treatment',''));
  v_new_baggage := lower(coalesce(p_facts->>'baggage_treatment',''));
  v_old_has := coalesce((v_old_facts->>'has_surfboard_policy')::boolean, false);
  v_new_has := coalesce((p_facts->>'has_surfboard_policy')::boolean, false);

  -- Hard holds: the updater should never silently replace good data in these cases.
  if coalesce(p_confidence,0) < 0.90 then
    v_reasons := array_append(v_reasons, 'Low extraction confidence (< 0.90)');
    v_hard_hold := true;
  end if;

  if v_old_has and not v_new_has then
    v_reasons := array_append(v_reasons, 'Previously had a surfboard policy; new extraction says no surfboard policy');
    v_hard_hold := true;
  end if;

  if v_old_baggage <> '' and v_new_baggage = 'unclear' then
    v_reasons := array_append(v_reasons, 'New baggage treatment became unclear');
    v_hard_hold := true;
  end if;

  if v_old_fee is not null and v_new_fee is null then
    v_reasons := array_append(v_reasons, 'Existing fee would be replaced by a blank fee');
    v_hard_hold := true;
  end if;

  if found and nullif(trim(coalesce(v_current.size_rule,'')), '') is not null
     and nullif(trim(coalesce(p_size_rule,'')), '') is null then
    v_reasons := array_append(v_reasons, 'Existing size rule would be replaced by a blank value');
    v_hard_hold := true;
  end if;

  -- Major treatment switches (free/included, paid special fee, not accepted) always require review.
  if v_old_baggage <> '' and v_new_baggage <> '' and v_old_baggage <> v_new_baggage then
    if v_old_baggage in ('included','normal_checked_bag','special_fee','not_accepted')
       or v_new_baggage in ('included','normal_checked_bag','special_fee','not_accepted') then
      v_reasons := array_append(v_reasons, 'Material baggage-treatment change: '||v_old_baggage||' -> '||v_new_baggage);
      v_hard_hold := true;
    else
      v_medium_change := true;
    end if;
  end if;

  -- Flag large numeric fee changes when both versions are stated in USD/$ terms.
  if v_old_fee is not null and v_new_fee is not null
     and (v_old_fee ~* 'USD' or position('$' in v_old_fee)>0)
     and (v_new_fee ~* 'USD' or position('$' in v_new_fee)>0) then
    begin
      v_old_amount := ((regexp_match(v_old_fee, '([0-9]+(?:[.][0-9]+)?)'))[1])::numeric;
      v_new_amount := ((regexp_match(v_new_fee, '([0-9]+(?:[.][0-9]+)?)'))[1])::numeric;
    exception when others then
      v_old_amount := null; v_new_amount := null;
    end;
    if v_old_amount is not null and v_new_amount is not null and v_old_amount <> v_new_amount then
      if abs(v_new_amount-v_old_amount) > 50
         or (v_old_amount > 0 and abs(v_new_amount-v_old_amount)/v_old_amount > 0.50) then
        v_reasons := array_append(v_reasons, 'Large fee change: '||v_old_amount||' -> '||v_new_amount);
        v_hard_hold := true;
      else
        v_medium_change := true;
      end if;
    end if;
  end if;

  if found and v_current.surf_rating_score is not null and p_surf_rating_score is not null
     and abs(v_current.surf_rating_score - p_surf_rating_score) >= 2 then
    v_reasons := array_append(v_reasons, 'Surf rating score changed by 2 or more points');
    v_hard_hold := true;
  end if;

  -- Medium-confidence extractions may auto-pass when nothing substantive changed,
  -- but a substantive change at <0.95 confidence is held for review.
  if coalesce(p_confidence,0) < 0.95 and v_medium_change then
    v_reasons := array_append(v_reasons, 'Material change with confidence below 0.95');
    v_hard_hold := true;
  end if;

  if v_hard_hold then
    v_severity := case when coalesce(p_confidence,0) < 0.90 then 'red' else 'yellow' end;
    select id into v_pending_id
      from public.airline_policy_qc_log
      where policy_url=p_policy_url and status='pending'
      order by created_at desc limit 1;

    if v_pending_id is not null then
      update public.airline_policy_qc_log
      set airline=coalesce(p_airline, v_current.airline), confidence=p_confidence,
          severity=v_severity, reasons=to_jsonb(v_reasons), old_snapshot=v_old_snapshot,
          proposed_payload=v_payload, created_at=now(), reviewed_at=null,
          review_action=null, review_notes=null
      where id=v_pending_id;
      v_log_id := v_pending_id;
    else
      insert into public.airline_policy_qc_log
        (airline,policy_url,confidence,severity,status,reasons,old_snapshot,proposed_payload)
      values
        (coalesce(p_airline, v_current.airline),p_policy_url,p_confidence,v_severity,'pending',to_jsonb(v_reasons),v_old_snapshot,v_payload)
      returning id into v_log_id;
    end if;

    return jsonb_build_object('action','held_for_review','qc_id',v_log_id,'severity',v_severity,'reasons',to_jsonb(v_reasons));
  end if;

  begin
    perform public.process_airline_policy_extraction_unchecked(
      p_policy_url, p_airline, p_facts, p_confidence,
      p_surfboard_treatment, p_size_rule, p_surf_rating_score,
      p_surf_rating, p_notes
    );

    insert into public.airline_policy_qc_log
      (airline,policy_url,confidence,severity,status,reasons,old_snapshot,proposed_payload,review_action)
    values
      (coalesce(p_airline, v_current.airline),p_policy_url,p_confidence,'green','auto_applied','[]'::jsonb,v_old_snapshot,v_payload,'auto')
    returning id into v_log_id;

    return jsonb_build_object('action','auto_applied','qc_id',v_log_id,'severity','green');
  exception when others then
    insert into public.airline_policy_qc_log
      (airline,policy_url,confidence,severity,status,reasons,old_snapshot,proposed_payload,review_action,review_notes)
    values
      (coalesce(p_airline, v_current.airline),p_policy_url,p_confidence,'red','apply_failed',jsonb_build_array('Existing updater function failed'),v_old_snapshot,v_payload,'failed',sqlerrm)
    returning id into v_log_id;
    return jsonb_build_object('action','apply_failed','qc_id',v_log_id,'severity','red','error',sqlerrm);
  end;
end $$;

revoke all on function public.process_airline_policy_extraction(text,text,jsonb,numeric,text,text,integer,text,text) from public, anon, authenticated;
grant execute on function public.process_airline_policy_extraction(text,text,jsonb,numeric,text,text,integer,text,text) to service_role;

-- Also protect the preserved unchecked updater from browser-side execution.
do $$
declare v_oid oid;
begin
  select p.oid into v_oid from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname='process_airline_policy_extraction_unchecked' and p.pronargs=9 limit 1;
  if v_oid is not null then
    execute format('revoke all on function %s from public, anon, authenticated', v_oid::regprocedure);
    execute format('grant execute on function %s to service_role', v_oid::regprocedure);
  end if;
end $$;

-- Quick verification query: after running this migration it should show two rows/functions.
select proname, oid::regprocedure as signature
from pg_proc
where pronamespace='public'::regnamespace
  and proname in ('process_airline_policy_extraction','process_airline_policy_extraction_unchecked')
order by proname;
