-- BoardBagFees.com — expand from 60 to 80 airlines
-- Prepared 2026-08-13 from current official airline sports-baggage pages.
-- Safe to run more than once. Weekly n8n updater remains the ongoing source-of-truth refresher.

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Royal Air Maroc','royal-air-maroc',61,'Connection',false,'Paid sports-equipment fee; surfboards accepted up to 300 cm with zone-based pricing','Up to 32 kg and 300 cm; published sports-equipment fee varies by route zone',2,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.royalairmaroc.com/us-en/sport-equipment','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('South African Airways','south-african-airways',62,'Connection',false,'Surfboards under 200 cm may travel as sporting equipment; excess-baggage charges can apply','Surfboards/kitesurfing equipment must be smaller than 200 cm; larger boards are cargo',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.flysaa.com/manage-fly/baggage/checked-baggage/special-baggage','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Airlink','airlink',63,'Connection',false,'Extra sporting-equipment allowance available for surf, kite, paddle and skateboards','Surf/kite/paddle/skate boards accepted up to 2 m in length; sporting-equipment allowance terms apply',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.flyairlink.com/baggage/sporting-equipment','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('FlySafair','flysafair',64,'Connection',false,'Paid sports-equipment item with a flat special-luggage charge','Maximum 32 kg; published sporting-equipment dimensions up to 250 × 80 × 75 cm',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.flysafair.co.za/travel-tools/extras/luggage-policy','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Kenya Airways','kenya-airways',65,'Connection',false,'Surf equipment is special baggage and may require advance clearance','Surf equipment over 107 cm is special baggage; over 32 kg or 300 cm is not accepted as passenger baggage',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.kenya-airways.com/en/plan/baggage-information/special-baggage/','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('SKY Airline','sky-airline',66,'Connection',false,'Paid special sports baggage; up to three sports items may be added','Surfboards may be up to 300 linear cm; weight limits vary by country and excess weight is charged',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.skyairline.com/es/chile/equipaje/articulos-prohibidos','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('JetSMART','jetsmart',67,'Connection',false,'Surfboards travel as oversized baggage with route- and purchase-time pricing','Up to 23 kg standard; surfboards exceptionally accepted up to 300 linear cm; excess weight up to 32 kg for a fee',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://jetsmart.com/us/en/opcionales/home','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Aerolíneas Argentinas','aerolineas-argentinas',68,'Connection',false,'Surfboards are accepted as special baggage; route-specific special-baggage charges apply','One surfboard bag with a board up to 300 cm long; special-baggage conditions apply',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.aerolineas.com.ar/en-eu/baggage-allowance?tab=special','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Volaris','volaris',69,'Connection',false,'Paid sports-equipment service; surfboards and similar boards are specifically accepted','Sports equipment up to 25 kg and 250 linear cm; maximum acceptance 45 kg and 280 linear cm with extra charges',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://cms.volaris.com/en/travel-info/baggage-policy/musical-instruments-and-sports-equipment/','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Viva Aerobus','viva-aerobus',70,'Connection',false,'Paid sports-baggage service','Sports equipment up to 71 lb and 126 linear in; handling fee applies',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.vivaaerobus.com/en-us/info/get-ready-to-fly/baggage-policies/special','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Lion Air','lion-air',71,'Connection',false,'Surfboards require a separate handling fee and are not covered by prepaid baggage','Surfboard handling is charged separately from prepaid baggage; verify aircraft and route limits before travel',2,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.lionair.co.id/en/manage-booking/prepaid-baggage','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Citilink','citilink',72,'Connection',false,'Surfboards are charged under Citilink sports-baggage tariffs','A320 surfboard length up to 227 cm; ATR 72-600 up to 170 cm; aircraft limits are important',2,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.citilink.co.id/en/bagasi-olahraga/','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Cebu Pacific','cebu-pacific',73,'Connection',false,'Paid CEB Special Baggage add-on specifically accepts surfboards','One special-baggage item per passenger with 20 kg base allowance; excess weight costs extra and Cebgo space can be limited',2,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://help.cebupacificair.com/article/ceb-special-baggage-143767','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Vueling','vueling',74,'Connection',false,'Surfboards are accepted as paid special luggage','Special luggage must be added to the booking; published online fee typically starts around €45–€65 each way',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.vueling.com/en/prepare-your-trip/luggage/special-equipment/','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Transavia','transavia',75,'Connection',false,'Dedicated water-sports baggage fee for surfboards, kiteboards and bodyboards','Up to 32 kg; mast + board up to 3.60 m; water-sports bag may contain only the sports equipment',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.transavia.com/help/en-eu/baggage/special-baggage/water-sports-equipment','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Norwegian','norwegian',76,'Connection',false,'Dedicated surfboard/kiting-equipment fee with cheaper online pricing','Maximum 23 kg; board bag up to 250 × 79 × 112 cm; sportswear must travel separately',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.norwegian.com/us/travel-info/baggage/sports-equipment/','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Condor','condor',77,'Connection',false,'Paid board sports equipment with zone-based pricing; advance registration required','Maximum 30 kg; accepted dimensions include up to 300 × 40 × 60 cm depending on equipment configuration',3,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.condor.com/us/flight-preparation/baggage-and-animals/sports-equipment.jsp','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Azores Airlines','azores-airlines',78,'Connection',false,'Published piece fee for surfboards and board sports; longboards have a higher fee on some routes','Surfboard, kiteboard and related board-sport categories have published sports-equipment rates; verify route-specific conditions',4,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.azoresairlines.pt/en/information/baggage/sporting-equipment','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Air Europa','air-europa',79,'Connection',false,'Surf equipment is not included in baggage allowance and carries a route-based surcharge','Maximum 23 kg standard, optionally up to 32 kg; maximum 250 linear cm for surf equipment',2,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.aireuropa.com/us/en/aea/travel-information/baggage/special-baggage/sports-equipment.html','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

insert into public.airline_surf_policies (airline,slug,sort_rank,service_type,serves_hnl,surfboard_treatment,size_rule,surf_rating_score,baggage_handling,policy_url,last_checked,policy_changed,agent_notes,active) values ('Aircalin','aircalin',80,'Connection',false,'Additional sports-equipment allowance on Aircalin-operated flights, including surfboards','Generally one additional sports-equipment piece up to 23 kg; surf/windsurf/paddle boards up to 3 m with advance request; some Pacific routes use a 10 kg sports allowance',5,'⚪ No directly comparable U.S. DOT airline-level baggage-handling data','https://www.aircalin.com/en/baggages/checked-baggages','2026-08-13',false,'Added in the 80-airline global expansion from the airline’s current official baggage/sports policy. Weekly automated structured extraction should refresh this baseline.',true)
on conflict (airline) do update set slug=excluded.slug, sort_rank=excluded.sort_rank, service_type=excluded.service_type, serves_hnl=excluded.serves_hnl, surfboard_treatment=excluded.surfboard_treatment, size_rule=excluded.size_rule, surf_rating_score=excluded.surf_rating_score, baggage_handling=excluded.baggage_handling, policy_url=excluded.policy_url, last_checked=excluded.last_checked, active=excluded.active;

-- Verify total active rows. Expect 80.
select count(*) as active_airlines from public.airline_surf_policies where active = true;

-- Show the 20 new rows.
select airline, slug, surf_rating_score, surf_rating, policy_url from public.airline_surf_policies where sort_rank between 61 and 80 order by sort_rank;