(() => {
  const loginCard=document.getElementById('loginCard'), queue=document.getElementById('queue'), cards=document.getElementById('cards');
  const loginStatus=document.getElementById('loginStatus'), queueStatus=document.getElementById('queueStatus');
  let password=sessionStorage.getItem('bbfAdminPassword')||'', currentStatus='pending';
  const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const stars=n=>'★'.repeat(Math.max(0,Math.min(5,Number(n)||0)))+'☆'.repeat(5-Math.max(0,Math.min(5,Number(n)||0)));
  const money=(v,c='USD')=>v==null?'':new Intl.NumberFormat('en-US',{style:'currency',currency:c||'USD'}).format(Number(v));
  const outcomeLabel={no_issue:'No issue',minor_damage:'Minor damage',major_damage:'Significant damage',board_broken:'Board broken',delayed:'Bag delayed',lost:'Bag lost'};
  const claimLabel={pending:'Claim pending',paid_full:'Claim paid/resolved',paid_partial:'Claim partially resolved',denied:'Claim denied',not_pursued:'Claim not pursued'};
  const api=async(path='',opts={})=>{const r=await fetch('/api/admin-reviews'+path,{...opts,headers:{'Content-Type':'application/json',Authorization:`Bearer ${password}`,...(opts.headers||{})},cache:'no-store'});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'Request failed');return out};
  function card(r){const meta=[r.airline_slug,r.route,r.trip_date,r.fee_paid==null?'':`Paid ${money(r.fee_paid,r.currency)}`,r.baggage_outcome?outcomeLabel[r.baggage_outcome]:'',r.claim_filed===true?'Claim filed':r.claim_filed===false?'No claim filed':'',r.claim_outcome?claimLabel[r.claim_outcome]:'',new Date(r.created_at).toLocaleString()].filter(Boolean).join(' · ');const damage=r.damage_details?`<div class="comment"><strong>Baggage details:</strong> ${esc(r.damage_details)}</div>`:'';return `<article class="review-card" data-id="${esc(r.id)}"><div class="review-top"><strong>${esc(r.display_name||'Anonymous surfer')}</strong><span class="badge">${esc(r.status)}</span></div><div class="stars">${stars(r.rating)}</div>${r.handling_rating?`<div class="handling-stars"><strong>Board/bag handling:</strong> ${stars(r.handling_rating)} <span>${Number(r.handling_rating)}/5</span></div>`:''}<div class="meta">${esc(meta)}</div><div class="comment">${esc(r.comment)}</div>${damage}<div class="actions"><label>Moderation note<textarea class="note" placeholder="Optional internal note">${esc(r.moderation_notes||'')}</textarea></label>${r.status!=='approved'?'<button class="approve">Approve</button>':''}${r.status!=='rejected'?'<button class="reject">Reject</button>':''}</div></article>`}
  async function load(){queueStatus.textContent='Loading…';try{const rows=await api(`?status=${encodeURIComponent(currentStatus)}&limit=100`);cards.innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No reports in this queue.</div>';queueStatus.textContent=`${rows.length} report${rows.length===1?'':'s'}`;loginCard.hidden=true;queue.hidden=false}catch(e){queueStatus.textContent='';loginStatus.textContent=e.message;loginCard.hidden=false;queue.hidden=true;sessionStorage.removeItem('bbfAdminPassword')}}
  async function update(cardEl,status){const btns=cardEl.querySelectorAll('button');btns.forEach(b=>b.disabled=true);queueStatus.textContent=`Saving ${status}…`;try{await api('',{method:'PATCH',body:JSON.stringify({id:cardEl.dataset.id,status,moderation_notes:cardEl.querySelector('.note').value})});await load()}catch(e){queueStatus.textContent=e.message;btns.forEach(b=>b.disabled=false)}}
  document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();password=document.getElementById('password').value;sessionStorage.setItem('bbfAdminPassword',password);loginStatus.textContent='';load()});
  document.querySelector('.tabs').addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(!b)return;document.querySelectorAll('.tabs [data-status]').forEach(x=>x.classList.toggle('active',x===b));currentStatus=b.dataset.status;load()});
  cards.addEventListener('click',e=>{const c=e.target.closest('.review-card');if(!c)return;if(e.target.closest('.approve'))update(c,'approved');if(e.target.closest('.reject'))update(c,'rejected')});
  document.getElementById('logout').addEventListener('click',()=>{sessionStorage.removeItem('bbfAdminPassword');password='';queue.hidden=true;loginCard.hidden=false;document.getElementById('password').value=''});
  if(password)load();
})();
